version: '3.8'
services:

  central-service:
    build: .
    ports:
      - "9070:8083"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    expose:
      - "5433"
    ports:
      - "5433:5432"
    command: -p 5433
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

