name: GITHUB-ACTIONS

on:
  push:
    branches:
      - master
      - main

jobs:
  test:
    name: Unit tests
    strategy:
      matrix:
        image_name: [ "central-warehouse-service","warehouse1-service","warehouse2-service","discovery-server" ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build with maven
        working-directory: ${{ matrix.image_name }}
        run: mvn -B package --file pom.xml
  docker:
    name: Build and deploy to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build with maven
        working-directory: ${{ matrix.image_name }}
        run: mvn -B package  ${{ matrix.image_name }}/pom.xml -DskipTests
      - name: Login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          content: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/inventory-management-restocking:latest



